const SERVER_DEFAULTS = {
  PORT: 11234,
  LOG_LEVEL: "info",
  PROGRESS_INTERVAL_MS: 5000,
};

const MOCHA_DEFAULTS = {
  TESTS_PATH: "",
  UI: "bdd",
};

const RUNNER_STATUS = {
  NOT_STARTED: "NOT_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  FINISHED: "FINISHED",
};

module.exports = {
  SERVER_DEFAULTS,
  MOCHA_DEFAULTS,
  RUNNER_STATUS,
};
